# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: "Security vulnerability scan"

on:
  workflow_dispatch:
  schedule:
    - cron: "50 1 * * *"

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # to fetch code (actions/checkout)
  contents: read

jobs:
  latest-deps:
    # Only run the scheduled job in hyperledger/fabric repository, not on personal forks
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository == 'hyperledger/fabric')
    runs-on: ${{ github.repository == 'hyperledger/fabric' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    strategy:
      fail-fast: false
      matrix:
        ref:
          - main
          - release-2.5
    steps:
      - name: Checkout ${{ matrix.ref }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.ref }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

  latest:
    needs:
      - latest-deps
    strategy:
      fail-fast: false
      matrix:
        ref:
          - main
          - release-2.5
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.0.0"
    with:
      scan-args: |-
        --lockfile=./go.mod
        --lockfile=./tools/go.mod
      matrix-property: ${{ matrix.ref }}-latest-
    permissions:
      security-events: write
      contents: read
      actions: read

  release-deps:
    # Only run the scheduled job in hyperledger/fabric repository, not on personal forks
    if: github.event_name != 'schedule' || (github.event_name == 'schedule' && github.repository == 'hyperledger/fabric')
    runs-on: ${{ github.repository == 'hyperledger/fabric' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    strategy:
      fail-fast: false
      matrix:
        ref:
          - main
          - release-2.5
    steps:
      - name: Checkout ${{ matrix.ref }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.ref }}
          fetch-depth: 0
      - name: Get latest release tag
        id: latest-release
        run: echo "tag=$(git -c versionsort.suffix=- tag --merged HEAD --sort=-version:refname | head -1)" >> "${GITHUB_OUTPUT}"
      - name: Checkout ${{ steps.latest-release.outputs.tag }}
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.latest-release.outputs.tag }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

  release:
    needs:
      - release-deps
    strategy:
      fail-fast: false
      matrix:
        ref:
          - main
          - release-2.5
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.0.0"
    with:
      scan-args: |-
        --lockfile=./go.mod
        --lockfile=./tools/go.mod
      matrix-property: ${{ matrix.ref }}-release-
    permissions:
      security-events: write
      contents: read
      actions: read
